env: "${ENV}" # This will be replaced by the ENV variable

mongodb:
  uri: "mongodb+srv://sa:Q8n%23FUpTpTkpK4%25@cdscluster1.b3chj.mongodb.net/?retryWrites=true&w=majority&appName=cdsCluster1"
  database: "custodian_db"
  profile_collection: "profiles"
  event_collection: "events"
  consent_collection: "consents"

port:
  http: 8080

