env: "${ENV}" # This will be replaced by the ENV variable

mongodb:
  uri: "${MONGODB_URI}"
  database: "custodian_db"
  profile_collection: "profiles"
  event_collection: "events"
  consent_collection: "consents"

addr:
  host: 0.0.0.0
  port: 8900

