// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package docs

import (
	"encoding/json"
	"errors"
	"time"

	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for EventEventType.
const (
	Identify EventEventType = "Identify"
	Page     EventEventType = "Page"
	Track    EventEventType = "Track"
)

// Defines values for IdentityDataAccountStatus.
const (
	Active    IdentityDataAccountStatus = "active"
	Inactive  IdentityDataAccountStatus = "inactive"
	Suspended IdentityDataAccountStatus = "suspended"
)

// Alias defines model for Alias.
type Alias struct {
	PreviousPermaId string `json:"previous_perma_id"`
}

// AppContext defines model for AppContext.
type AppContext struct {
	AppId          *string   `json:"app_id,omitempty"`
	AppPermissions *[]string `json:"app_permissions,omitempty"`
	Devices        *[]struct {
		Browser        *string    `json:"browser,omitempty"`
		BrowserVersion *string    `json:"browser_version,omitempty"`
		DeviceId       *string    `json:"device_id,omitempty"`
		DeviceType     *string    `json:"device_type,omitempty"`
		Ip             *string    `json:"ip,omitempty"`
		LastUsed       *time.Time `json:"last_used,omitempty"`
		Os             *string    `json:"os,omitempty"`
	} `json:"devices,omitempty"`
	FeatureFlags *struct {
		BetaFeaturesEnabled *bool `json:"beta_features_enabled,omitempty"`
		DarkMode            *bool `json:"dark_mode,omitempty"`
	} `json:"feature_flags,omitempty"`
	LastActiveApp   *string `json:"last_active_app,omitempty"`
	RegionsAccessed *[]struct {
		City          *string    `json:"city,omitempty"`
		Country       *string    `json:"country,omitempty"`
		FirstAccessed *time.Time `json:"first_accessed,omitempty"`
		LastAccessed  *time.Time `json:"last_accessed,omitempty"`
		Timezone      *string    `json:"timezone,omitempty"`
	} `json:"regions_accessed,omitempty"`
	SubscriptionPlan *string `json:"subscription_plan,omitempty"`
	UsageMetrics     *struct {
		DailyActiveTime *int `json:"daily_active_time,omitempty"`
		MonthlyLogins   *int `json:"monthly_logins,omitempty"`
	} `json:"usage_metrics,omitempty"`
}

// Consent defines model for Consent.
type Consent struct {
	Collect []openapi_types.UUID `json:"collect"`
	Share   []openapi_types.UUID `json:"share"`
}

// Event defines model for Event.
type Event struct {
	// AppId Unique ID for the application
	AppId openapi_types.UUID `json:"app_id"`

	// Context Device and session information
	Context map[string]interface{} `json:"context"`

	// EventId Unique ID for the event
	EventId openapi_types.UUID `json:"event_id"`

	// EventName Name of the event
	EventName string `json:"event_name"`

	// EventTimestamp Time at which the event occurred
	EventTimestamp time.Time `json:"event_timestamp"`

	// EventType Type of the event
	EventType EventEventType `json:"event_type"`

	// Locale User's language and regional settings
	Locale     *string           `json:"locale,omitempty"`
	Properties *Event_Properties `json:"properties,omitempty"`
}

// EventEventType Type of the event
type EventEventType string

// Event_Properties defines model for Event.Properties.
type Event_Properties struct {
	union json.RawMessage
}

// IdentifyEvent Event properties for user identity tracking
type IdentifyEvent struct {
	// Traits Custom user attributes
	Traits *map[string]interface{} `json:"traits,omitempty"`

	// UserId Unique identifier for the user
	UserId *openapi_types.UUID `json:"user_id,omitempty"`
}

// IdentityData defines model for IdentityData.
type IdentityData struct {
	AccountStatus     *IdentityDataAccountStatus `json:"account_status,omitempty"`
	CreatedAt         *time.Time                 `json:"created_at,omitempty"`
	DisplayName       *string                    `json:"display_name,omitempty"`
	Email             *openapi_types.Email       `json:"email,omitempty"`
	FirstName         *string                    `json:"first_name,omitempty"`
	Groups            *[]string                  `json:"groups,omitempty"`
	IdpProvider       *string                    `json:"idp_provider,omitempty"`
	LastLogin         *time.Time                 `json:"last_login,omitempty"`
	LastName          *string                    `json:"last_name,omitempty"`
	Locale            *string                    `json:"locale,omitempty"`
	MfaEnabled        *bool                      `json:"mfa_enabled,omitempty"`
	PhoneNumbers      *[]string                  `json:"phone_numbers,omitempty"`
	Picture           *string                    `json:"picture,omitempty"`
	PreferredUsername *string                    `json:"preferred_username,omitempty"`
	ProfileUrl        *string                    `json:"profile_url,omitempty"`
	Roles             *[]string                  `json:"roles,omitempty"`
	Timezone          *string                    `json:"timezone,omitempty"`
	UpdatedAt         *time.Time                 `json:"updated_at,omitempty"`
	Username          *string                    `json:"username,omitempty"`
}

// IdentityDataAccountStatus defines model for IdentityData.AccountStatus.
type IdentityDataAccountStatus string

// PageEvent Event properties for page interactions
type PageEvent struct {
	Engagement *struct {
		// EngagementScore Custom engagement score
		EngagementScore *float32 `json:"engagement_score,omitempty"`

		// InteractiveElements List of interactive elements clicked
		InteractiveElements *[]string `json:"interactive_elements,omitempty"`
	} `json:"engagement,omitempty"`
	Page *struct {
		// ContentType Type of content (e.g., article, video)
		ContentType *string `json:"content_type,omitempty"`

		// PageCategory Logical category of the page
		PageCategory *string `json:"page_category,omitempty"`

		// PageType Type of page (e.g., landing_page, blog)
		PageType *string `json:"page_type,omitempty"`

		// Path Page path without domain
		Path *string `json:"path,omitempty"`

		// PreviousPage Identifier for the previous page
		PreviousPage *string `json:"previous_page,omitempty"`

		// Referrer URL of the previous page
		Referrer *string `json:"referrer,omitempty"`

		// ScrollDepth Percentage of page scrolled
		ScrollDepth *string `json:"scroll_depth,omitempty"`

		// Search Query parameters from the URL
		Search *string `json:"search,omitempty"`

		// TimeOnPage Time spent on the page in seconds
		TimeOnPage *int `json:"time_on_page,omitempty"`

		// Title Title of the page
		Title *string `json:"title,omitempty"`

		// Url Full URL of the page
		Url *string `json:"url,omitempty"`
	} `json:"page,omitempty"`
	Utm *struct {
		// Campaign Campaign name
		Campaign *string `json:"campaign,omitempty"`

		// Medium Marketing medium (e.g., email, social)
		Medium *string `json:"medium,omitempty"`

		// Source Traffic source (e.g., google, facebook)
		Source *string `json:"source,omitempty"`
	} `json:"utm,omitempty"`
}

// PersonalityData defines model for PersonalityData.
type PersonalityData struct {
	CommunicationPreferences *struct {
		EmailNotifications *bool `json:"email_notifications,omitempty"`
		PushNotifications  *bool `json:"push_notifications,omitempty"`
		SmsNotifications   *bool `json:"sms_notifications,omitempty"`
	} `json:"communication_preferences,omitempty"`
	Interests           *[]string `json:"interests,omitempty"`
	PreferredLanguage   *string   `json:"preferred_language,omitempty"`
	ShoppingPreferences *struct {
		DiscountPreference *string   `json:"discount_preference,omitempty"`
		FavoriteBrands     *[]string `json:"favorite_brands,omitempty"`
	} `json:"shopping_preferences,omitempty"`
}

// ProfileData defines model for ProfileData.
type ProfileData struct {
	AppContext    *[]AppContext         `json:"app_context,omitempty"`
	Identity      *IdentityData         `json:"identity,omitempty"`
	OriginCountry string                `json:"originCountry"`
	Personality   *PersonalityData      `json:"personality,omitempty"`
	UserIds       *[]openapi_types.UUID `json:"user_ids,omitempty"`
}

// ProfileDataWithoutAppContext defines model for ProfileDataWithoutAppContext.
type ProfileDataWithoutAppContext struct {
	Identity      *IdentityData         `json:"identity,omitempty"`
	OriginCountry string                `json:"originCountry"`
	Personality   *PersonalityData      `json:"personality,omitempty"`
	UserIds       *[]openapi_types.UUID `json:"user_ids,omitempty"`
}

// TrackEvent Event properties for tracking user interactions
type TrackEvent struct {
	// Action The specific action performed (click, scroll)
	Action *string `json:"action,omitempty"`

	// Label Additional label for categorization
	Label *string `json:"label,omitempty"`

	// ObjectId Unique identifier for the interacted object
	ObjectId *string `json:"object_id,omitempty"`

	// ObjectName Human-readable name of the object
	ObjectName *string `json:"object_name,omitempty"`

	// ObjectType The type of object interacted with (button, product)
	ObjectType *string `json:"object_type,omitempty"`

	// Referrer URL of the referring page
	Referrer *string `json:"referrer,omitempty"`

	// Source Source of the interaction (website, mobile app)
	Source *string `json:"source,omitempty"`

	// Url URL where the event occurred
	Url *string `json:"url,omitempty"`

	// Value A numeric value associated with the event
	Value *float32 `json:"value,omitempty"`
}

// BindUserToProfileJSONBody defines parameters for BindUserToProfile.
type BindUserToProfileJSONBody = []openapi_types.UUID

// GiveConsentToCollectJSONBody defines parameters for GiveConsentToCollect.
type GiveConsentToCollectJSONBody = []openapi_types.UUID

// GiveConsentToShareJSONBody defines parameters for GiveConsentToShare.
type GiveConsentToShareJSONBody = []openapi_types.UUID

// GetProfileDataParams defines parameters for GetProfileData.
type GetProfileDataParams struct {
	// IncludeAppContext Whether to include application context data
	IncludeAppContext *bool `form:"includeAppContext,omitempty" json:"includeAppContext,omitempty"`

	// AppId Application ID for fetching profile data with app context
	AppId *openapi_types.UUID `form:"app_id,omitempty" json:"app_id,omitempty"`
}

// GetUserEventsParams defines parameters for GetUserEvents.
type GetUserEventsParams struct {
	// SearchString Optional search filter
	SearchString *string `form:"searchString,omitempty" json:"searchString,omitempty"`

	// Offset Number of records to skip for pagination
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`

	// Limit Maximum number of records to return
	Limit *int32 `form:"limit,omitempty" json:"limit,omitempty"`
}

// GetUserEventParams defines parameters for GetUserEvent.
type GetUserEventParams struct {
	// SearchString Optional search filter
	SearchString *string `form:"searchString,omitempty" json:"searchString,omitempty"`

	// Offset Number of records to skip for pagination
	Offset *int `form:"offset,omitempty" json:"offset,omitempty"`

	// Limit Maximum number of records to return
	Limit *int32 `form:"limit,omitempty" json:"limit,omitempty"`
}

// CreateProfileJSONRequestBody defines body for CreateProfile for application/json ContentType.
type CreateProfileJSONRequestBody = ProfileData

// AliasUserJSONRequestBody defines body for AliasUser for application/json ContentType.
type AliasUserJSONRequestBody = Alias

// BindUserToProfileJSONRequestBody defines body for BindUserToProfile for application/json ContentType.
type BindUserToProfileJSONRequestBody = BindUserToProfileJSONBody

// GiveConsentToCollectJSONRequestBody defines body for GiveConsentToCollect for application/json ContentType.
type GiveConsentToCollectJSONRequestBody = GiveConsentToCollectJSONBody

// GiveConsentToShareJSONRequestBody defines body for GiveConsentToShare for application/json ContentType.
type GiveConsentToShareJSONRequestBody = GiveConsentToShareJSONBody

// AddPersonalityDataJSONRequestBody defines body for UpdatePersonalityData for application/json ContentType.
type AddPersonalityDataJSONRequestBody = PersonalityData

// AddPersonalityDataJSONRequestBody defines body for UpdatePersonalityData for application/json ContentType.
type AddPersonalityDataJSONRequestBody = PersonalityData

// AddAppContextDataJSONRequestBody defines body for AddAppContextData for application/json ContentType.
type AddAppContextDataJSONRequestBody = AppContext

// AddAppContextDataJSONRequestBody defines body for AddAppContextData for application/json ContentType.
type AddAppContextDataJSONRequestBody = AppContext

// AddEventJSONRequestBody defines body for AddEvent for application/json ContentType.
type AddEventJSONRequestBody = Event

// AddEventsJSONRequestBody defines body for AddEvents for application/json ContentType.
type AddEventsJSONRequestBody = Event

// AsPageEvent returns the union data inside the Event_Properties as a PageEvent
func (t Event_Properties) AsPageEvent() (PageEvent, error) {
	var body PageEvent
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromPageEvent overwrites any union data inside the Event_Properties as the provided PageEvent
func (t *Event_Properties) FromPageEvent(v PageEvent) error {
	v.EventType = "Page"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergePageEvent performs a merge with any union data inside the Event_Properties, using the provided PageEvent
func (t *Event_Properties) MergePageEvent(v PageEvent) error {
	v.EventType = "Page"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsTrackEvent returns the union data inside the Event_Properties as a TrackEvent
func (t Event_Properties) AsTrackEvent() (TrackEvent, error) {
	var body TrackEvent
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromTrackEvent overwrites any union data inside the Event_Properties as the provided TrackEvent
func (t *Event_Properties) FromTrackEvent(v TrackEvent) error {
	v.EventType = "Track"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeTrackEvent performs a merge with any union data inside the Event_Properties, using the provided TrackEvent
func (t *Event_Properties) MergeTrackEvent(v TrackEvent) error {
	v.EventType = "Track"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

// AsIdentifyEvent returns the union data inside the Event_Properties as a IdentifyEvent
func (t Event_Properties) AsIdentifyEvent() (IdentifyEvent, error) {
	var body IdentifyEvent
	err := json.Unmarshal(t.union, &body)
	return body, err
}

// FromIdentifyEvent overwrites any union data inside the Event_Properties as the provided IdentifyEvent
func (t *Event_Properties) FromIdentifyEvent(v IdentifyEvent) error {
	v.EventType = "Identify"
	b, err := json.Marshal(v)
	t.union = b
	return err
}

// MergeIdentifyEvent performs a merge with any union data inside the Event_Properties, using the provided IdentifyEvent
func (t *Event_Properties) MergeIdentifyEvent(v IdentifyEvent) error {
	v.EventType = "Identify"
	b, err := json.Marshal(v)
	if err != nil {
		return err
	}

	merged, err := runtime.JSONMerge(t.union, b)
	t.union = merged
	return err
}

func (t Event_Properties) Discriminator() (string, error) {
	var discriminator struct {
		Discriminator string `json:"event_type"`
	}
	err := json.Unmarshal(t.union, &discriminator)
	return discriminator.Discriminator, err
}

func (t Event_Properties) ValueByDiscriminator() (interface{}, error) {
	discriminator, err := t.Discriminator()
	if err != nil {
		return nil, err
	}
	switch discriminator {
	case "Identify":
		return t.AsIdentifyEvent()
	case "Page":
		return t.AsPageEvent()
	case "Track":
		return t.AsTrackEvent()
	default:
		return nil, errors.New("unknown discriminator value: " + discriminator)
	}
}

func (t Event_Properties) MarshalJSON() ([]byte, error) {
	b, err := t.union.MarshalJSON()
	return b, err
}

func (t *Event_Properties) UnmarshalJSON(b []byte) error {
	err := t.union.UnmarshalJSON(b)
	return err
}
